xsd2php:
  namespaces:
      'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd': 'GoetasWebservices\SoapServices\SoapClient\WssWsSecurity\Secext'
      'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd': 'GoetasWebservices\SoapServices\SoapClient\WssWsSecurity\Utility'
      'http://www.w3.org/2000/09/xmldsig#': 'GoetasWebservices\SoapServices\SoapClient\WssWsSecurity\XmlSign'
  destinations_php:
    'GoetasWebservices\SoapServices\SoapClient\WssWsSecurity': src/WssWsSecurity
  destinations_jms:
    'GoetasWebservices\SoapServices\SoapClient\WssWsSecurity': src/Resources/metadata/wss-ws-security
  known_locations:
    'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd': ws-security/oasis-200401-wss-wssecurity-utility-1.0.xsd
    'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd': ws-security/oasis-200401-wss-wssecurity-secext-1.0.xsd
    'https://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd': ws-security/xmldsig-core-schema.xsd
    'http://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd': ws-security/xmldsig-core-schema.xsd
  any_element: true
  any_attribute: true
