GoetasWebservices\SoapServices\SoapClient\WssWsSecurity\Secext\Security:
    xml_root_name: Security
    xml_root_namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'
